#!/usr/bin/env bash
# server-dev.sh — Run ai-proxy in service mode: Vite frontend (1420) + Rust backend (7860) together.
#
# Reuses the existing standalone `ai-proxy-server` binary (no Tauri/webview).
# Auto-provisions AI_PROXY_JWT_SECRET on first run, uses a local data dir.
#
# Usage:
#   pnpm server:dev
#   AI_PROXY_DATA_DIR=/tmp/ai-proxy PORT=7870 pnpm server:dev
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# --- 1. Data dir: share with Tauri desktop dev mode ----------------------
# Default to the same directory Tauri uses in debug builds (`com.aiproxy.app-dev`).
# Override via AI_PROXY_DATA_DIR if needed.
TAURI_DATA_DIR="$HOME/Library/Application Support/com.aiproxy.app-dev"
DATA_DIR="${AI_PROXY_DATA_DIR:-$TAURI_DATA_DIR}"
export AI_PROXY_DATA_DIR="$DATA_DIR"
mkdir -p "$DATA_DIR"

# --- 2. Ensure .env exists with JWT secret + admin password (reuse if present) --
# Stored in the data dir so the JWT secret persists alongside the shared database.
ENV_FILE="$DATA_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "→ Generating $ENV_FILE with a fresh AI_PROXY_JWT_SECRET and AI_PROXY_ADMIN_PASSWORD ..."
  {
    echo "# Auto-generated by scripts/server-dev.sh — do NOT commit (.env is gitignored)."
    echo "AI_PROXY_JWT_SECRET=\"$(openssl rand -hex 32)\""
    echo "# Admin login password for the web UI (user: admin). Edit this value to change it."
    echo "AI_PROXY_ADMIN_PASSWORD=\"admin\""
  } > "$ENV_FILE"
  echo "  (default admin password is 'admin' — change AI_PROXY_ADMIN_PASSWORD in .env to customize)"
fi

# Export every VAR=VALUE in .env so child processes (cargo run) inherit them.
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

# Backfill AI_PROXY_ADMIN_PASSWORD into a legacy .env (older versions only wrote the JWT secret),
# so the password below is never blank.
if [[ -z "${AI_PROXY_ADMIN_PASSWORD:-}" ]]; then
  echo "AI_PROXY_ADMIN_PASSWORD=\"admin\"" >> "$ENV_FILE"
  AI_PROXY_ADMIN_PASSWORD="admin"
  echo "  (added default AI_PROXY_ADMIN_PASSWORD=admin to .env)"
fi

# --- 3. Ports ---------------------------------------------------------------
# Use a dedicated var (not the generic PORT, which may be set in the shell env
# or picked up by Vite) so the backend reliably binds 7860.
HOST="${AI_PROXY_HOST:-127.0.0.1}"
PORT="${AI_PROXY_PORT:-7860}"

# --- 4. Launch backend (server feature, no Tauri) in background ------------
echo "→ Starting backend on ${HOST}:${PORT} (data dir: ${DATA_DIR})"
echo "  Note: first build of the \`server\` feature may take a while."
cargo run \
  --manifest-path "$PROJECT_ROOT/src-tauri/Cargo.toml" \
  --bin ai-proxy-server \
  --no-default-features \
  --features server \
  -- --host "$HOST" --port "$PORT" &
BACKEND_PID=$!

cleanup() {
  echo
  echo "→ Stopping backend (pid ${BACKEND_PID}) ..."
  kill "$BACKEND_PID" 2>/dev/null || true
  wait "$BACKEND_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# --- 5. Launch frontend (Vite, 1420) in foreground -------------------------
echo "→ Starting frontend on http://localhost:1420"
echo "  Admin login:  user=admin  password=${AI_PROXY_ADMIN_PASSWORD:-<random, see backend logs>}"
echo "  (change it via AI_PROXY_ADMIN_PASSWORD in .env; first run only creates the user)"
# fg: Ctrl+C reaches Vite, trap kills the backend on exit.
pnpm dev
